#conexion a la bd //BRM
 # url: jdbc:mysql://localhost/java:3306/proyectost?allowPublicKeyRetrieval=true&useSSL=false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proyectost?allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    username: root
    password: 666666
  jpa:
  #muestra las consultas sql en terminal
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
 